{
 "title": "Content-Cache-K8s Operator",
 "description": "Dashboard for the Content-Cache-K8s Operator, powered by Juju.",
 "tags": [
  "nginx",
  "prometheus",
  "nginx prometheus exporter"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\"},juju_model_uuid)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_application=\"$juju_application\"},juju_unit)"
    }
   },
   { "name": "prometheusds", "query": "prometheus" },
   { "name": "lokids", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "NGINX Status for $juju_unit",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nginx_up{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\"}"
    }
   ]
  },
  {
   "title": "Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Processed connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections (rate)" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_connections_accepted{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\"}[5m])",
     "legendFormat": " accepted"
    },
    {
     "expr": "irate(nginx_connections_handled{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\"}[5m])",
     "legendFormat": " handled"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Connections" }
   ],
   "targets": [
    {
     "expr": "nginx_connections_active{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\"}",
     "legendFormat": " active"
    },
    {
     "expr": "nginx_connections_reading{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\"}",
     "legendFormat": " reading"
    },
    {
     "expr": "nginx_connections_waiting{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\"}",
     "legendFormat": " waiting"
    },
    {
     "expr": "nginx_connections_writing{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\"}",
     "legendFormat": " writing"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(nginx_http_requests_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\"}[5m])",
     "legendFormat": " total requests"
    }
   ]
  },
  {
   "title": "Cache Requests (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "count by(filename) (count_over_time({filename=\"/var/log/nginx/access.log\"} | pattern `<ip> <_> <_> <_> \"<method> <uri> <_>\" <status> <size> <_> \"<agent>\" <_> <cache_status> <_>` | __error__=`` | cache_status != `-` [24h]))"
    }
   ]
  },
  {
   "title": "Cache Misses (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "count by(filename) (count_over_time({filename=\"/var/log/nginx/access.log\"} | pattern `<ip> <_> <_> <_> \"<method> <uri> <_>\" <status> <size> <_> \"<agent>\" <_> <cache_status> <_>` | __error__=`` | cache_status = `MISS` [24h]))"
    }
   ]
  },
  {
   "title": "Cache Hits (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "count by(filename) (count_over_time({filename=\"/var/log/nginx/access.log\"} | pattern `<ip> <_> <_> <_> \"<method> <uri> <_>\" <status> <size> <_> \"<agent>\" <_> <cache_status> <_>` | __error__=`` | cache_status = `HIT` [24h]))"
    }
   ]
  },
  {
   "title": "Cache Updating (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "count by(filename) (count_over_time({filename=\"/var/log/nginx/access.log\"} | pattern `<ip> <_> <_> <_> \"<method> <uri> <_>\" <status> <size> <_> \"<agent>\" <_> <cache_status> <_>` | __error__=`` | cache_status = `UPDATING` [24h]))"
    }
   ]
  },
  {
   "title": "Stale Cache Hits (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "count by(filename) (count_over_time({filename=\"/var/log/nginx/access.log\"} | pattern `<ip> <_> <_> <_> \"<method> <uri> <_>\" <status> <size> <_> \"<agent>\" <_> <cache_status> <_>` | __error__=`` | cache_status = `STALE` [24h]))"
    }
   ]
  },
  {
   "title": "Cache Revalidated (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "count by(filename) (count_over_time({filename=\"/var/log/nginx/access.log\"} | pattern `<ip> <_> <_> <_> \"<method> <uri> <_>\" <status> <size> <_> \"<agent>\" <_> <cache_status> <_>` | __error__=`` | cache_status = `REVALIDATED` [24h]))"
    }
   ]
  },
  {
   "title": "Cache Bypasses (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "count by(filename) (count_over_time({filename=\"/var/log/nginx/access.log\"} | pattern `<ip> <_> <_> <_> \"<method> <uri> <_>\" <status> <size> <_> \"<agent>\" <_> <cache_status> <_>` | __error__=`` | cache_status = `BYPASS` [24h]))"
    }
   ]
  },
  {
   "title": "Cache Expires (24h)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "count by(filename) (count_over_time({filename=\"/var/log/nginx/access.log\"} | pattern `<ip> <_> <_> <_> \"<method> <uri> <_>\" <status> <size> <_> \"<agent>\" <_> <cache_status> <_>` | __error__=`` | cache_status = `EXPIRED` [24h]))"
    }
   ]
  }
 ]
}