name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      juju-channel: 3/stable
      channel: 1.29-strict/stable
      setup-devstack-swift: true
      trivy-image-config: "trivy.yaml"
      extra-arguments: "--openstack-rc=${GITHUB_WORKSPACE}/openrc"
