name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Devstack Swift
        id: setup-devstack-swift
        uses: canonical/setup-devstack-swift@v1

      - name: Create OpenStack credential file
        run: echo "${{ steps.setup-devstack-swift.outputs.credentials }}" > openrc

      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s

      - name: Enable microk8s plugins
        run: |
          sudo microk8s enable registry hostpath-storage ingress
          sudo microk8s kubectl -n kube-system rollout status -w deployment/hostpath-provisioner
          sudo microk8s kubectl -n container-registry rollout status -w deployment/registry
          sudo microk8s kubectl -n ingress rollout status -w daemonset.apps/nginx-ingress-microk8s-controller

      - name: Dump microk8s config
        run: sudo microk8s config > kube-config

      - name: Install tox
        run: python3 -m pip install tox

      - name: Install tox, skopeo and docker
        run: |
          sudo snap install --edge rockcraft --classic
          sudo apt-get install skopeo

      - name: Build rock image
        working-directory: ./content-cache_rock
        run: |
          rockcraft
          skopeo --insecure-policy copy oci-archive:content-cache_latest_amd64.rock docker-daemon:localhost:32000/content-cache:test
          docker push localhost:32000/content-cache:test

      - name: Run integration tests
        run: >
          tox -e integration --
          --openstack-rc=${GITHUB_WORKSPACE}/openrc
          --content-cache-image="localhost:32000/content-cache:test"
