name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      setup-devstack-swift: true
      trivy-image-config: "trivy.yaml"
      juju-channel: 3/stable
      channel: 1.31-strict/stable
      extra-arguments: "--openstack-rc=${GITHUB_WORKSPACE}/openrc"
      tmate-debug: true
      tmate-timeout: 180
