name: Integration tests

on:
  pull_request:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@main
    secrets: inherit
    with:
      setup-devstack-swift: true
      trivy-image-config: "trivy.yaml"
      juju-channel: 3.6/stable
      channel: 1.34-strict/stable
      extra-arguments: "--openstack-rc=${GITHUB_WORKSPACE}/openrc"
      self-hosted-runner: true  
  allure-report:
    if: always() && !cancelled()
    needs:
      - integration-tests
    uses: canonical/operator-workflows/.github/workflows/allure_report.yaml@main
