name: Integration tests

on:
  push:

jobs:
  integration-tests:
    uses: canonical/operator-workflows/.github/workflows/integration_test.yaml@fix/conditional-export-secret-env
    secrets: inherit
    with:
      setup-devstack-swift: true
      trivy-image-config: "trivy.yaml"
      juju-channel: 3/stable
      channel: 1.29-strict/stable
      extra-arguments: "--openstack-rc=${GITHUB_WORKSPACE}/openrc"
